// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSxvg64gzzWtO4EZK5_F73XI0iN8x5tvI',
    appId: '1:253545303174:web:965f5fc39b8270549cd507',
    messagingSenderId: '253545303174',
    projectId: 'chatapp-17e42',
    authDomain: 'chatapp-17e42.firebaseapp.com',
    storageBucket: 'chatapp-17e42.firebasestorage.app',
    measurementId: 'G-MCGZ3VERLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx2BM_uy80RlY5JDA1bBwQE0Xq6-4zp9E',
    appId: '1:253545303174:android:625ce3cb2ec96ebd9cd507',
    messagingSenderId: '253545303174',
    projectId: 'chatapp-17e42',
    storageBucket: 'chatapp-17e42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmPSB1Oxr6kP0Faz-lm8rtTgt18XuRc88',
    appId: '1:253545303174:ios:b12334311502787f9cd507',
    messagingSenderId: '253545303174',
    projectId: 'chatapp-17e42',
    storageBucket: 'chatapp-17e42.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmPSB1Oxr6kP0Faz-lm8rtTgt18XuRc88',
    appId: '1:253545303174:ios:b12334311502787f9cd507',
    messagingSenderId: '253545303174',
    projectId: 'chatapp-17e42',
    storageBucket: 'chatapp-17e42.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSxvg64gzzWtO4EZK5_F73XI0iN8x5tvI',
    appId: '1:253545303174:web:63f701164c0a79c59cd507',
    messagingSenderId: '253545303174',
    projectId: 'chatapp-17e42',
    authDomain: 'chatapp-17e42.firebaseapp.com',
    storageBucket: 'chatapp-17e42.firebasestorage.app',
    measurementId: 'G-FW67RVKMGM',
  );

}